project_id = "ihwjbvzynygkvvbqiths"

[functions.text-to-speech]
verify_jwt = false

[functions.palm-analysis]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.generate-reading]
verify_jwt = false
